[features]
seeds = false
skip-lint = false
[programs.localnet]
ecs = "F3xobt75aXdrk3oRiK3JpPepZAswNmeid8rkLtZTkrqK"
dominariworld = "GGNoo8tn1vbLnMwU9Hz4oFmNXQd2gVpXCG9m3ZT7LK1J"
dominarisystems = "Gp1okeWiTe7PK58aiEdMWgQQp5DCYAkh223dARExNf1Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/spacemandev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
