[features]
seeds = false
skip-lint = false
[programs.localnet]
ecs = "GN5Ww5qa8ej4evFCJxMhV6AFEPKhD1Drdu8qYYptVgDJ"
dominariworld = "H5mieGWWK6qukHoNzbR6ysLxReeQC4JHZcNM6JkPQnm3"
dominarisystems = "3YdayPtujByJ1g1DWEUh7vpg78gZL49FWyD5rDGyof9T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/spacemandev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
